version: "3"

networks:
  loki:

services:
  loki:
    container_name: loki
    image: grafana/loki:2.9.2
    ports:
      - "3100:3100"
    command: -config.file=/etc/loki/local-config.yaml
    networks:
      - loki
    restart: unless-stopped

  promtail:
    container_name: promtail
    image: grafana/promtail:2.9.2
    volumes:
      - /var/log:/var/log
      - /etc/promtail/config.yml:/etc/promtail/config.yml
      - /var/lib/docker/containers/
    command: -config.file=/etc/promtail/config.yml
    networks:
      - loki
    restart: unless-stopped

  grafana:
    container_name: grafana
    environment:
      - GF_PATHS_PROVISIONING=/etc/grafana/provisioning
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
    entrypoint:
      - sh
      - -euc
      - |
        mkdir -p /etc/grafana/provisioning/datasources
        cat <<EOF > /etc/grafana/provisioning/datasources/ds.yaml
        apiVersion: 1
        datasources:
        - name: Loki
          type: loki
          access: proxy 
          orgId: 1
          url: http://loki:3100
          basicAuth: false
          isDefault: true
          version: 1
          editable: false
        EOF
        /run.sh
    image: grafana/grafana:latest
    ports:
      - "3000:3000"
    networks:
      - loki
    restart: unless-stopped

  helloworld-container:
    container_name: hei
    image: lillebomartin/hei-1:v1.0.0
    networks:
      - loki
    logging:
      driver: "loki"
      options:
        loki-url: "http://localhost:3100/loki/api/v1/push"
    restart: unless-stopped
